export const addItemControls = [
    {
        id: "itemName",
        type: "text",
        placeholder: "Enter Item Name",
        value: "itemName",
        label: "Item Name",
        componentType: "input",
    },
    {
        id: "img1",
        type: "text",
        placeholder: "Enter First image URL",
        value: "img1",
        label: "First Image URL",
        componentType: "input",
    },
    {
        id: "img2",
        type: "text",
        placeholder: "Enter secound image URL",
        value: "img2",
        label: "Secound Image URL",
        componentType: "input",
    },
    {
        id: "img3",
        type: "text",
        placeholder: "Enter Third image URL",
        value: "img3",
        label: "Third Image URL",
        componentType: "input",
    },
    {
        id: "price",
        type: "text",
        placeholder: "Enter Item Price",
        value: "price",
        label: "Item Price",
        componentType: "input",
    },
    {
        id: "dropDown",
        type: "dropDown",
        placeholder: "Enter Item Availability",
        value: "dropDown",
        label: "",
        componentType: "dropDown",
    },
    {
        id: "itemType",
        type: "text",
        placeholder: "Enter Item Type",
        value: "itemType",
        label: "Item Type",
        componentType: "input",
    },
    {
        id: "description",
        type: "text",
        placeholder: "Enter Item description",
        value: "description",
        label: "description",
        componentType: "input",
    },
]