import { Inter } from "next/font/google";
import "./globals.css";
import NavBar from "./components/NavBar";
import Toast from "./components/ToastMessage";
import GlobalState from "./context";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  manifest: "/manifest.json",
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">

      <body className={inter.className}>
        <GlobalState>
          <NavBar />
          <main className="">
            {children}
          </main>
        </GlobalState>
        <Toast />
      </body>
    </html>
  );
}
